name: Build and Deploy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o ./bin/linux/server ./cmd/server
        working-directory: ./

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ./bin/windows/server.exe ./cmd/server
        working-directory: ./

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./bin
